[WIP] DO NOT MERGE - RFE-600 - Add SameSite annotation via route
openshift/router pull request #189
Opened 2020-09-19 17:18 UTC by miheer

Fix to add annotation for same site via route

2020-09-22 21:03 UTC, Miciah commented on images/router/haproxy/Dockerfile
> +ENTRYPOINT ["/usr/bin/openshift-router", "--", "--v=4"]
These changes should be dropped.

2020-09-22 21:13 UTC, Miciah commented
This needs a BZ associated.  Let's use [BZ#1867186](https://bugzilla.redhat.com/show_bug.cgi?id=1867186).
/retitle Bug 1867186: Add SameSite route annotation

2020-09-23 03:33 UTC, miheer commented on images/router/haproxy/conf/haproxy-config.template
> +    {{- end }}
OK thanks a lot Miciah! But I am worried if there won't be any side effects of having strict as a default behavior ?

Or may be set it to None as default ?
As per https://hacks.mozilla.org/2020/08/changes-to-samesite-cookie-behavior/
None – The browser will send cookies with both cross-site and same-site requests.
Strict – The browser will only send cookies for same-site requests (i.e., requests originating from the site that set the cookie).
Lax – Cookies will be withheld on cross-site requests (such as calls to load images or frames). However, cookies will be sent when a user navigates to the URL from an external site; for example, by following a link.

2020-09-23 03:33 UTC, miheer commented on images/router/haproxy/Dockerfile
> +ENTRYPOINT ["/usr/bin/openshift-router", "--", "--v=4"]
ACK

2020-09-23 04:35 UTC, Miciah commented on images/router/haproxy/conf/haproxy-config.template
> +    {{- end }}
Sorry, that's right.  According to the design document, the default should be `None` for compatibility.  (If we don't specify `SameSite` at all, it defaults to `Lax`.)

2020-09-23 14:08 UTC, Miciah requested changes
You forgot to remove a couple redundant lines, but otherwise this looks fine to me.

2020-09-23 14:08 UTC, Miciah commented on images/router/haproxy/conf/haproxy-config.template
>      {{- end }}
Delete these two lines.

2020-09-23 16:51 UTC, frobware commented
Is it possible to add any unit testing for this change?

2020-09-25 03:02 UTC, miheer commented
/test e2e

2020-09-25 03:02 UTC, miheer commented
/test e2e-upgrade

2020-09-25 04:46 UTC, miheer commented
/test e2e

2020-09-28 17:27 UTC, Miciah commented
/lgtm

2020-09-28 17:37 UTC, Miciah commented
/bugzilla refresh

2020-09-28 17:39 UTC, Miciah commented
/retitle Bug 1867186: Add SameSite route annotation

2020-09-28 17:39 UTC, Miciah commented
/bugzilla refresh

2020-09-29 19:26 UTC, merged